?read.table
?mean
?list.files
list.files("specdata", "*.csv")
mean(c(1,2,3,4,5,6,7))
r001 <- read.csv("specdata/001.csv")
View(r001)
View(r001)
nrows(r001)
nrow(r001)
readings <- r001$sulfate[!is.na(r001$sulfate)]
mean(readings)
sum(readings)
length(readings)
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
source("Week2Assignment.R")
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
pollutantmean("specdata", "sulfate", 1:5)
pollutantmean("specdata", "sulfate", 1:5)
source("Week2Assignment.R")
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
source("Week2Assignment.R")
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
?paste
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:5)
pollutantmean("specdata", "sulfate", 1:1)
pollutantmean("specdata", "sulfate")
pollutantmean("specdata", "nitrate")
source("Week2Assignment.R")
pollutantmean("specdata", "nitrate")
source("Week2Assignment.R")
pollutantmean("specdata", "nitrate")
pollutantmean("specdata", "sulfate")
source("Week2Assignment.R")
pollutantmean("specdata", "sulfate", 1:10)
pollutantmean("specdata", "nitrate", 70:72)
pollutantmean("specdata", "nitrate", 23)
savehistory("~/GitHub/RProgramming/Week2Assignment1History.R")
